import { Template } from 'meteor/templating'
import { Beamer } from '../../../contexts/beamer/Beamer'
import { Routes } from '../../../api/routes/Routes'
import '../../layout/navSide/navSide'
import '../../layout/main/main'
import '../../layout/routeInfo/routeInfo'
import '../../layout/footer/footer'
import './teacherContainer.scss'
import './teacherContainer.html'

export const teacherContainer = 'teacherContainer'
