name: Test suite

on:
  push:
    branches:
      - master
      - release-*
  pull_request:

jobs:
  lintCode:
    name: Javascript lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-

      - name: run Biome lint+format checks
        working-directory: src
        run: |
          npm ci
          npm run lint:code
          npm run format:code

  lintStyle:
    name: SCSS lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-
      - name: run stylelint
        working-directory: src
        run: |
          npm ci
          npm run lint:style

  tests:
    name: Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Install Meteor
        id: cache-meteor-install
        uses: actions/cache@v5
        with:
          path: ~/.meteor
          key: v1-meteor-${{ hashFiles('.meteor/versions') }}
          restore-keys: |
            v1-meteor-
      - name: Cache NPM dependencies
        id: cache-meteor-npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-

      - name: Cache Meteor build
        id: cache-meteor-build
        uses: actions/cache@v5
        with:
          path: |
            .meteor/local/resolver-result-cache.json
            .meteor/local/plugin-cache
            .meteor/local/isopacks
            .meteor/local/bundler-cache/scanner
          key: v1-meteor_build_cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            v1-meteor_build_cache-
      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '3.4'

        # uses -o for running once -c for coverage
      - name: Run Tests
        working-directory: src
        run: |
          meteor npm ci
          sh ./scripts/test.sh -o -p
